all:
	gcc sleep_example.c -o sleep_example
	gcc simple_threading_timer.c -o simple_threading_timer -lrt
	gcc signal_interrupt_timer.c -o signal_interrupt_timer -lrt

clean:
	rm sleep_example
	rm simple_threading_timer
	rm signal_interrupt_timer
