#include <syslog.h>

int main(int argc, char **argv)
{
    openlog("GetIoT", LOG_CONS | LOG_PID, 0);
    syslog(LOG_DEBUG, "Syslog test message generated by '%s'/n", argv[0]);
    closelog();
    return 0;
}