all:
	gcc raw_socket_example.c -o raw_socket_example
	gcc ping_example.c -o ping_example
	gcc raw_socket_send_udp.c -o raw_socket_send_udp

clean:
	rm raw_socket_example
	rm ping_example
	rm raw_socket_send_udp