all:
	gcc asctime_sample.c -o asctime_sample
	gcc gettimeofday_sample.c -o gettimeofday_sample
	gcc localtime_sample.c -o localtime_sample
	gcc time_sample.c -o time_sample
	gcc ctime_sample.c -o ctime_sample
	gcc gmtime_sample.c -o gmtime_sample
	gcc mktime.c -o mktime
	gcc timeval_to_tm.c -o timeval_to_tm

clean:
	rm asctime_sample
	rm gettimeofday_sample
	rm localtime_sample
	rm time_sample
	rm ctime_sample
	rm gmtime_sample
	rm mktime
	rm timeval_to_tm